In [4]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv('data.csv')
data.head()

,Image,Class,Mean,Variance,Standard Deviation,Entropy,Skewness,Kurtosis,Contrast,Energy,ASM,Homogeneity,Dissimilarity,Correlation,Coarseness
0,Image1,0,6.535339,619.587845,24.891522,0.109059,4.276477,18.900575,98.613971,0.293314,0.086033,0.530941,4.473346,0.981939,7.458341e-155
1,Image2,0,8.749969,805.957634,28.389393,0.266538,3.718116,14.464618,63.858816,0.475051,0.225674,0.651352,3.220072,0.988834,7.458341e-155
2,Image3,1,7.341095,1143.808219,33.820234,0.001467,5.061750,26.479563,81.867206,0.031917,0.001019,0.268275,5.981800,0.978014,7.458341e-155
3,Image4,1,5.958145,959.711985,30.979219,0.001477,5.677977,33.428845,151.229741,0.032024,0.001026,0.243851,7.700919,0.964189,7.458341e-155
4,Image5,0,7.315231,729.540579,27.010009,0.146761,4.283221,19.079108,174.988756,0.343849,0.118232,0.501140,6.834689,0.972789,7.458341e-155

In [6]:
data = data.drop(['Image'],axis=1)
data.head()

,Class,Mean,Variance,Standard Deviation,Entropy,Skewness,Kurtosis,Contrast,Energy,ASM,Homogeneity,Dissimilarity,Correlation,Coarseness
0,0,6.535339,619.587845,24.891522,0.109059,4.276477,18.900575,98.613971,0.293314,0.086033,0.530941,4.473346,0.981939,7.458341e-155
1,0,8.749969,805.957634,28.389393,0.266538,3.718116,14.464618,63.858816,0.475051,0.225674,0.651352,3.220072,0.988834,7.458341e-155
2,1,7.341095,1143.808219,33.820234,0.001467,5.061750,26.479563,81.867206,0.031917,0.001019,0.268275,5.981800,0.978014,7.458341e-155
3,1,5.958145,959.711985,30.979219,0.001477,5.677977,33.428845,151.229741,0.032024,0.001026,0.243851,7.700919,0.964189,7.458341e-155
4,0,7.315231,729.540579,27.010009,0.146761,4.283221,19.079108,174.988756,0.343849,0.118232,0.501140,6.834689,0.972789,7.458341e-155

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
scaler = StandardScaler()
scaler.fit(data.drop(['Class'],axis=1))
dataFit = scaler.transform(data.drop(['Class'],axis=1))

lastData = pd.DataFrame(dataFit,columns = data.columns[1:])
lastData.head()

,Mean,Variance,Standard Deviation,Entropy,Skewness,Kurtosis,Contrast,Energy,ASM,Homogeneity,Dissimilarity,Correlation,Coarseness
0,-0.515700,-0.195790,-0.033144,0.504650,0.067855,-0.097267,-0.268050,0.685118,0.470073,0.404100,-0.121709,1.000713,-1.117857e-168
1,-0.129018,0.202943,0.365594,2.746050,-0.150204,-0.175881,-0.585492,2.090287,2.865580,1.345457,-0.799181,1.264377,-1.117857e-168
2,-0.375013,0.925765,0.984680,-1.026708,0.374531,0.037048,-0.421010,-1.335981,-0.988340,-1.649391,0.693704,0.850636,-1.117857e-168
3,-0.616481,0.531896,0.660820,-1.026561,0.615188,0.160202,0.212525,-1.335154,-0.988223,-1.840334,1.622995,0.322041,-1.117857e-168
4,-0.379529,0.039451,0.208352,1.041256,0.070489,-0.094103,0.429532,1.075849,1.022442,0.171115,1.154744,0.650854,-1.117857e-168

In [9]:
from sklearn.model_selection import train_test_split

X = lastData
Y = data['Class']

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.5)

In [12]:
from tensorflow import keras


model = keras.Sequential()

model.add(keras.layers.Dense(256,activation='relu', input_shape =(13,)))
model.add(keras.layers.Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [13]:
model.fit(X_train,Y_train,epochs=5,batch_size=1,verbose=1)

Epoch 1/5
1881/1881 [==============================] - 1s 605us/step - loss: 0.0932 - accuracy: 0.9718
Epoch 2/5
1881/1881 [==============================] - 1s 594us/step - loss: 0.0624 - accuracy: 0.9771
Epoch 3/5
1881/1881 [==============================] - 1s 599us/step - loss: 0.0546 - accuracy: 0.9793
Epoch 4/5
1881/1881 [==============================] - 1s 585us/step - loss: 0.0503 - accuracy: 0.9819
Epoch 5/5
1881/1881 [==============================] - 1s 584us/step - loss: 0.0488 - accuracy: 0.9819

In [43]:
test_loss, test_acc = model.evaluate(X_test, Y_test)
print(test_acc)

59/59 [==============================] - 0s 569us/step - loss: 0.0453 - accuracy: 0.9825
0.9824561476707458

In [18]:
test_loss, test_acc = model.evaluate(X_train, Y_train)
print(test_acc)

95/95 [==============================] - 0s 628us/step - loss: 0.0024 - accuracy: 0.9997
0.9996676445007324