In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [3]:
#Loading the data

raw_data = pd.read_csv('weatherAUS.csv')
raw_data['RainToday'] = raw_data['RainToday'].map({'Yes':1, 'No':0})
raw_data['RainTomorrow'] = raw_data['RainTomorrow'].map({'Yes':1, 'No':0})
raw_data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,0.0,0.0
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,0.0,0.0
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,0.0,0.0
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,0.0,0.0
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,0.0,0.0

In [4]:
raw_data.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [5]:
#Picking the Sydney data

sydney_raw_data = raw_data[raw_data['Location'] == 'Sydney']
sydney_raw_data = sydney_raw_data.drop(['Date','Location','WindGustDir','WindDir9am','WindDir3pm'],axis=1)
sydney_raw_data = sydney_raw_data.dropna(thresh = len(sydney_raw_data)*0.8,axis=1)
sydney_raw_data = sydney_raw_data.dropna()
sydney_raw_data

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
30176,19.5,22.4,15.6,6.2,0.0,17.0,20.0,92.0,84.0,1017.6,1017.4,8.0,8.0,20.7,20.9,1.0,1.0
30177,19.5,25.6,6.0,3.4,2.7,9.0,13.0,83.0,73.0,1017.9,1016.4,7.0,7.0,22.4,24.8,1.0,1.0
30178,21.6,24.5,6.6,2.4,0.1,17.0,2.0,88.0,86.0,1016.7,1015.6,7.0,8.0,23.5,23.0,1.0,1.0
30179,20.2,22.8,18.8,2.2,0.0,22.0,20.0,83.0,90.0,1014.2,1011.8,8.0,8.0,21.4,20.9,1.0,1.0
30181,20.2,27.2,1.6,2.6,8.6,9.0,22.0,69.0,62.0,1002.7,998.6,6.0,6.0,23.8,26.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33515,8.6,19.6,0.0,2.0,7.8,22.0,20.0,73.0,52.0,1025.9,1025.3,2.0,2.0,10.5,17.9,0.0,0.0
33516,9.3,19.2,0.0,2.0,9.2,20.0,7.0,78.0,53.0,1028.5,1024.6,2.0,2.0,11.0,18.7,0.0,0.0
33517,9.4,17.7,0.0,2.4,2.7,15.0,13.0,85.0,56.0,1020.8,1015.0,6.0,6.0,10.2,17.3,0.0,0.0
33518,10.1,19.3,0.0,1.4,9.3,17.0,19.0,56.0,35.0,1017.3,1015.1,5.0,2.0,12.4,19.0,0.0,0.0
33519,7.6,19.3,0.0,3.4,9.4,13.0,13.0,73.0,32.0,1018.6,1015.4,1.0,1.0,9.4,18.8,0.0,0.0

In [6]:
from sklearn.preprocessing import MinMaxScaler

#Scaling the model between 0 and 1

scaler = MinMaxScaler()
sydney_raw_data = pd.DataFrame(scaler.fit_transform(sydney_raw_data), columns=sydney_raw_data.columns)
sydney_raw_data.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,0.666667,0.313783,0.165254,0.336957,0.000000,0.386364,0.40,0.901235,0.870588,0.590822,0.592998,0.888889,1.000,0.475083,0.310145,1.0,1.0
1,0.666667,0.407625,0.063559,0.184783,0.198529,0.204545,0.26,0.790123,0.741176,0.596558,0.571116,0.777778,0.875,0.531561,0.423188,1.0,1.0
2,0.758772,0.375367,0.069915,0.130435,0.007353,0.386364,0.04,0.851852,0.894118,0.573614,0.553611,0.777778,1.000,0.568106,0.371014,1.0,1.0
3,0.697368,0.325513,0.199153,0.119565,0.000000,0.500000,0.40,0.790123,0.941176,0.525813,0.470460,0.888889,1.000,0.498339,0.310145,1.0,1.0
4,0.697368,0.454545,0.016949,0.141304,0.632353,0.204545,0.44,0.617284,0.611765,0.305927,0.181619,0.666667,0.750,0.578073,0.457971,1.0,1.0

In [7]:
from sklearn.model_selection import train_test_split

#Splitting the data to test & train sets

x = sydney_raw_data.drop(['RainTomorrow'],axis=1)
y = sydney_raw_data['RainTomorrow']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=11)

In [8]:
#Creating the model

model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(16,activation='relu',input_shape=(len(x_train.columns),)),
    tf.keras.layers.Dense(32,activation='relu'),
    tf.keras.layers.Dense(64,activation='relu'),
    tf.keras.layers.Dense(32,activation='relu'),
    tf.keras.layers.Dense(16,activation='relu'),
    tf.keras.layers.Dense(1,activation='sigmoid')
])

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

model.fit(x_train,y_train,epochs=50)

Epoch 1/50
67/67 [==============================] - 1s 879us/step - loss: 0.5689 - accuracy: 0.7281
Epoch 2/50
67/67 [==============================] - 0s 803us/step - loss: 0.4391 - accuracy: 0.8071
Epoch 3/50
67/67 [==============================] - 0s 818us/step - loss: 0.4163 - accuracy: 0.8199
Epoch 4/50
67/67 [==============================] - 0s 788us/step - loss: 0.4076 - accuracy: 0.8203
Epoch 5/50
67/67 [==============================] - 0s 803us/step - loss: 0.4023 - accuracy: 0.8189
Epoch 6/50
67/67 [==============================] - 0s 855us/step - loss: 0.3941 - accuracy: 0.8270
Epoch 7/50
67/67 [==============================] - 0s 803us/step - loss: 0.3945 - accuracy: 0.8265
Epoch 8/50
67/67 [==============================] - 0s 832us/step - loss: 0.3882 - accuracy: 0.8279
Epoch 9/50
67/67 [==============================] - 0s 818us/step - loss: 0.3866 - accuracy: 0.8307
Epoch 10/50
67/67 [==============================] - 0s 873us/step - loss: 0.3832 - accuracy: 0.8312
Epoch 11/50
67/67 [==============================] - 0s 864us/step - loss: 0.3781 - accuracy: 0.8317
Epoch 12/50
67/67 [==============================] - 0s 803us/step - loss: 0.3802 - accuracy: 0.8355
Epoch 13/50
67/67 [==============================] - 0s 803us/step - loss: 0.3789 - accuracy: 0.8322
Epoch 14/50
67/67 [==============================] - 0s 788us/step - loss: 0.3758 - accuracy: 0.8340
Epoch 15/50
67/67 [==============================] - 0s 788us/step - loss: 0.3751 - accuracy: 0.8350
Epoch 16/50
67/67 [==============================] - 0s 803us/step - loss: 0.3757 - accuracy: 0.8397
Epoch 17/50
67/67 [==============================] - 0s 849us/step - loss: 0.3750 - accuracy: 0.8326
Epoch 18/50
67/67 [==============================] - 0s 833us/step - loss: 0.3757 - accuracy: 0.8392
Epoch 19/50
67/67 [==============================] - 0s 788us/step - loss: 0.3702 - accuracy: 0.8411
Epoch 20/50
67/67 [==============================] - 0s 833us/step - loss: 0.3714 - accuracy: 0.8355
Epoch 21/50
67/67 [==============================] - 0s 788us/step - loss: 0.3684 - accuracy: 0.8407
Epoch 22/50
67/67 [==============================] - 0s 788us/step - loss: 0.3641 - accuracy: 0.8397
Epoch 23/50
67/67 [==============================] - 0s 803us/step - loss: 0.3714 - accuracy: 0.8397
Epoch 24/50
67/67 [==============================] - 0s 864us/step - loss: 0.3632 - accuracy: 0.8426
Epoch 25/50
67/67 [==============================] - 0s 848us/step - loss: 0.3689 - accuracy: 0.8345
Epoch 26/50
67/67 [==============================] - 0s 818us/step - loss: 0.3701 - accuracy: 0.8369
Epoch 27/50
67/67 [==============================] - 0s 803us/step - loss: 0.3599 - accuracy: 0.8435
Epoch 28/50
67/67 [==============================] - 0s 788us/step - loss: 0.3633 - accuracy: 0.8416
Epoch 29/50
67/67 [==============================] - 0s 818us/step - loss: 0.3659 - accuracy: 0.8355
Epoch 30/50
67/67 [==============================] - 0s 803us/step - loss: 0.3605 - accuracy: 0.8426
Epoch 31/50
67/67 [==============================] - 0s 788us/step - loss: 0.3567 - accuracy: 0.8397
Epoch 32/50
67/67 [==============================] - 0s 788us/step - loss: 0.3600 - accuracy: 0.8402
Epoch 33/50
67/67 [==============================] - 0s 849us/step - loss: 0.3572 - accuracy: 0.8454
Epoch 34/50
67/67 [==============================] - 0s 849us/step - loss: 0.3594 - accuracy: 0.8459
Epoch 35/50
67/67 [==============================] - 0s 833us/step - loss: 0.3559 - accuracy: 0.8440
Epoch 36/50
67/67 [==============================] - 0s 788us/step - loss: 0.3620 - accuracy: 0.8397
Epoch 37/50
67/67 [==============================] - 0s 818us/step - loss: 0.3552 - accuracy: 0.8435
Epoch 38/50
67/67 [==============================] - 0s 788us/step - loss: 0.3536 - accuracy: 0.8440
Epoch 39/50
67/67 [==============================] - 0s 803us/step - loss: 0.3528 - accuracy: 0.8478
Epoch 40/50
67/67 [==============================] - 0s 849us/step - loss: 0.3593 - accuracy: 0.8407
Epoch 41/50
67/67 [==============================] - 0s 894us/step - loss: 0.3511 - accuracy: 0.8478
Epoch 42/50
67/67 [==============================] - 0s 833us/step - loss: 0.3541 - accuracy: 0.8473
Epoch 43/50
67/67 [==============================] - 0s 803us/step - loss: 0.3505 - accuracy: 0.8473
Epoch 44/50
67/67 [==============================] - 0s 833us/step - loss: 0.3475 - accuracy: 0.8482
Epoch 45/50
67/67 [==============================] - 0s 803us/step - loss: 0.3512 - accuracy: 0.8487
Epoch 46/50
67/67 [==============================] - 0s 833us/step - loss: 0.3468 - accuracy: 0.8463
Epoch 47/50
67/67 [==============================] - 0s 833us/step - loss: 0.3528 - accuracy: 0.8426
Epoch 48/50
67/67 [==============================] - 0s 803us/step - loss: 0.3455 - accuracy: 0.8459
Epoch 49/50
67/67 [==============================] - 0s 841us/step - loss: 0.3499 - accuracy: 0.8487
Epoch 50/50
67/67 [==============================] - 0s 818us/step - loss: 0.3502 - accuracy: 0.8435

In [9]:
#Testing the model

model.evaluate(x_test,y_test)

17/17 [==============================] - 0s 748us/step - loss: 0.3650 - accuracy: 0.8393

[0.36499014496803284, 0.8393194675445557]

In [13]:
#save the model
model.save('weather_model.h5')

#load the model

#model = tf.keras.models.load_model('weather_model.h5')

#predict

#predictions = model.predict(x_test)

#predictions = np.round(predictions)

#predictions[:10]

#y_test[:10]